spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://ep-aged-forest-ah14iyzm-pooler.c-3.us-east-1.aws.neon.tech/productdb?sslmode=require&channel_binding=require
#    username: neondb_owner
#    password: npg_6XNAU7efLhEl
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
#ep-aged-forest-ah14iyzm-pooler.c-3.us-east-1.aws.neon.tech/productdb?sslmode=require&channel_binding=require